security:
  jwt:
    secret: mySecret
    header: Authorization
    headerPrefix: Bearer
    expiration: 864_000_000
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/alljava
    username: root
    password: root
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
logging:
  level:
    com:
      medkhelifi: trace
    org:
      springframework:
        web: trace
      hibernate:
        type: trace
