CREATE TABLE role (
                      ID_ROLE INT(11) NOT NULL AUTO_INCREMENT,
                      ROLE VARCHAR(45) NOT NULL,
                      DESCRIPTION VARCHAR(45) DEFAULT NULL,
                      PRIMARY KEY (ID_ROLE)
) ENGINE=INNODB AUTO_INCREMENT=5 DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;

--
-- DUMPING DATA FOR TABLE ROLE
--

INSERT INTO role VALUES (1,'ROLE_SUPER_ADMIN','SUPER ADMINISTRATEUR'),(2,'ROLE_ADMIN','ADMINISTRATEUR'),(3,'ROLE_USER','UTILISATEUR');

CREATE TABLE users (
                       ID_USER INT(11) NOT NULL AUTO_INCREMENT,
                       FIRSTNAME VARCHAR(45) NOT NULL,
                       LASTNAME VARCHAR(45) NOT NULL,
                       EMAIL VARCHAR(45) NOT NULL,
                       PASSWORD VARCHAR(150) NOT NULL,
                       PRIMARY KEY (ID_USER)
) ENGINE=INNODB AUTO_INCREMENT=2 DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;

--
-- DUMPING DATA FOR TABLE USER
--
INSERT INTO users VALUES (1,'Super','Admin','admin@gmail.com','{bcrypt}$2a$10$rqRUoWtazBtoE5Pb6DkoueSa6mtxnWTWTrhVfFll.7K2JR20TGUU6');

CREATE TABLE user_role (
                           ID_USER INT(11) NOT NULL,
                           ID_ROLE INT(11) NOT NULL,
                           PRIMARY KEY (ID_USER,ID_ROLE),
                           KEY FK_USER_ROLE_ROLE_IDX (ID_ROLE) /*!80000 INVISIBLE */,
                           CONSTRAINT FK_USER_ROLE_ROLE FOREIGN KEY (ID_ROLE) REFERENCES role (ID_ROLE) ON DELETE CASCADE ON UPDATE CASCADE,
                           CONSTRAINT FK_USER_ROLE_USER FOREIGN KEY (ID_USER) REFERENCES users (ID_USER)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4 COLLATE=UTF8MB4_0900_AI_CI;

--
-- DUMPING DATA FOR TABLE USER_ROLE
--

INSERT INTO user_role VALUES (1,2);
